# Dependencies
markdown:         kramdown
highlighter:      rouge

include: ['_pages']
permalink: /:title/

# Permalinks
relative_permalinks: false

# Setup
title:            Nathan Brooks
tagline:          'Roboticist'
description:      ' '
url:              https://nbbrooks.github.io
baseurl:             /

author:
  name:           'Nathan Brooks'
  github:         https://github.com/nbbrooks
  linkedin:       https://www.linkedin.com/in/nathan-b-brooks


paginate:         5

# Custom vars
version:          2.1.0
